package com.example.E_commerceUribe.ayudas;

public enum DepartamentoCliente {
    Antioquia,
    Amazonas,
    Arauca,
    Atlántico,
    Bolívar,
    Boyacá,
    Caldas,
    Caquetá,
    Casanare,
    Cauca,
    Cesar,
    Chocó,
    Córdoba,
    Cundinamarca,
    Guainía,
    Guaviare,
    Huila,
    La_Guajira,
    Magdalena,
    Meta,
    Nariño,
    Norte_de_Santander,
    Putumayo,
    Quindío,
    Risaralda,
    San_Andrés_y_Providencia,
    Santander,
    Sucre,
    Tolima,
    Valle_del_Cauca,
    Vaupés,
    Vichada
}
